### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by GunmanDE** [ArmaSocialClub/ASC_MultiTrainingsMission.VR#1]
following files are missing 

#include "W_Teleporter\CfgFunctions.hpp"	// W_Teleporter functions
#include "W_Teleporter\dialog.hpp"	// W_Teleporter dialog

by the way, why W_??? 

ascinsignia.paa missing too

**Comment by Quentin0815** [comment]
fixed. folders weren't included in upload so they were just skipped.
it's a script by a [W] member, so it's his credit.
